-- CreateEnum
CREATE TYPE "ProjectType" AS ENUM ('AUDIT_REVIEW_CORPORATE_LAW', 'AUDIT_REVIEW_TAX_LAW', 'AUDIT_REVIEW_LISTING_REGULATIONS', 'MANAGEMENT_AUDIT', 'OTHER_ASSURANCE_SERVICES');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "materiality" TEXT,
ADD COLUMN     "period" TEXT,
ADD COLUMN     "type" "ProjectType" NOT NULL DEFAULT 'AUDIT_REVIEW_CORPORATE_LAW';
